### PR TITLE
Suggestions for unblocking

### PR DESCRIPTION
**Pull request by sonylnagale**
This should work for delete, but there is still a problem which I'd like _you_ to solve (just so that I'm not doing all the fixing for you): when you try to do two reservations without refreshing the page, there is an error. See if you can figure it out!

### CODE REVIEW

**Review by graphimatic — APPROVED** [review]

**Comment by graphimatic** [comment]
hi sonyl,
how do I get this updated file on my local folder with the command line?

**Comment by sonylnagale** [comment]
You can hit `merge` and then do `git pull` from command line!

**Comment by graphimatic** [comment]
git pull origin master?

**Comment by sonylnagale** [comment]
Yes, since you're only concerned with master you can do `git pull origin master`.

**Comment by graphimatic** [comment]
git pull origin master?

**Comment by graphimatic** [comment]
errr.... I always seem to hit a wall when using terminal. Here's what i'm getting:

A-Ts-iMac:graphimatic.github.io ana$ git pull origin master
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by graphimatic** [comment]
It says merged on here...

**Comment by sonylnagale** [comment]
Can I see the output of `git status` ? You shouldn't have anything in red.

**Comment by graphimatic** [comment]
A-Ts-iMac:graphimatic.github.io ana$ git status
On branch sonylnagale-master
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   Unit9_project/js/main.js

no changes added to commit (use "git add" and/or "git commit -a")
A-Ts-iMac:graphimatic.github.io ana$

**Comment by sonylnagale** [comment]
I think I see now.

`git reset --hard`
`git fetch --all`
`git pull`
`git checkout master`

**Pull request merged**
